apiVersion: v1
kind: Service
metadata:
  name: mysvc
spec:
  type: LoadBalancer
  ports:
  - protocol: "TCP"
    targetPort: 80 # exposed port of container [Dockerfile], for convenience, the `targetPort` is set to the same value as the `port` field.
    port: 80 # clusterIP port
  selector:
    env: test
