apiVersion: v1
kind: Service
metadata:
  name: mysvc
spec:
  type: NodePort
  ports:
  - targetPort: 80 # exposed port of container [Dockerfile], for convenience, the `targetPort` is set to the same value as the `port` field.
    port: 80 # clusterIP port
    nodePort: 32000 # range 30000 - 32767
  selector:
    env: test
