apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replica # pod-replica name
  #namespace: vicky
  labels:
    env: rstest # desired label for rs
spec:
  replicas: 3
  selector:
    matchLabels:
      env: test # selector -> matchLabels == template -> labels
  template: # selector matchLabels must be a match [same] as labels
    metadata:
      name: pod-httpd
      namespace: vicky
      labels:
        env: test
    spec:
      containers:
      - name: httpd-con
        image: httpd


