apiVersion: v1
kind: ConfigMap # configmap are used as volumeMounts [dyanamic value] 
metadata:
  name: my-configmap
data:
  db-port: "3306"

####################

### DEPLOYMENT.YML ###

deployment.ymlapiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy # pod-deploy name
  #namespace: vicky
  labels:
    env: test-deploy # desired label for deployment
spec:
  replicas: 2
  selector:
    matchLabels: # replica label
      env: test # replica label == pod label
  template: # selector matchLabels must be a match [same] as labels
    metadata:
      name: nginx-pod
      labels: # pod label
        env: test # pod label == replica label
    spec:
      containers:
      - name: nginx-con
        image: nginx
        volumeMounts:
        - name: my-volume # container level created container metadata name
          mountPath: /opt # desired path in container
      volumes:
      - name: my-volume # container level volume creation inside container
        configMap: # read volume from configmap
          name: my-configmap # configmap metadata name
        ports:
        - containerPort: 80
